apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: concession
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: front-end
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: front-end
    spec:
      containers:
      - env:
        - name: COMPONENT_BACKEND_HOST
          value: backend
        - name: COMPONENT_BACKEND_PORT
          value: "8080"
        image: front-end
        imagePullPolicy: IfNotPresent
        name: front-end
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30