apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end
    app.kubernetes.io/component: front-end
    app.kubernetes.io/instance: front-end
  name: front-end
  namespace: concession
spec:
  clusterIP: 172.30.244.123
  clusterIPs:
  - 172.30.244.123
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: front-end
  sessionAffinity: None
  type: ClusterIP
