apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: frontend
  name: frontend
  namespace: concession
spec:
  clusterIP: 172.30.244.123
  clusterIPs:
  - 172.30.244.123
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: frontend
  sessionAffinity: None
  type: ClusterIP
